In [33]:
from __future__ import absolute_import, division, print_function
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras
from keras import optimizers
print(tf.__version__)

2.17.0


In [34]:
data1 = pd.read_csv("london_merged.csv", skiprows = 0)
data1.head()


timestamp  cnt   t1   t2    hum  wind_speed  weather_code  \
0  2015-01-04 00:00:00  182  3.0  2.0   93.0         6.0           3.0   
1  2015-01-04 01:00:00  138  3.0  2.5   93.0         5.0           1.0   
2  2015-01-04 02:00:00  134  2.5  2.5   96.5         0.0           1.0   
3  2015-01-04 03:00:00   72  2.0  2.0  100.0         0.0           1.0   
4  2015-01-04 04:00:00   47  2.0  0.0   93.0         6.5           1.0   

   is_holiday  is_weekend  season  
0         0.0         1.0     3.0  
1         0.0         1.0     3.0  
2         0.0         1.0     3.0  
3         0.0         1.0     3.0  
4         0.0         1.0     3.0

In [40]:
#17,000 rows of data
len(data1)

17405

In [35]:
data1['cnt'].median()

844.0

In [36]:
#split cnt variable by median 
data1.loc[data1['cnt'] < 844, 'cnt_group'] = 0 #low 
data1.loc[data1['cnt'] > 844, 'cnt_group'] = 1 #medium
data1 = data1[np.isfinite(data1['cnt_group'])]
data1.tail()

timestamp   cnt   t1   t2   hum  wind_speed  weather_code  \
17409  2017-01-03 19:00:00  1042  5.0  1.0  81.0        19.0           3.0   
17410  2017-01-03 20:00:00   541  5.0  1.0  81.0        21.0           4.0   
17411  2017-01-03 21:00:00   337  5.5  1.5  78.5        24.0           4.0   
17412  2017-01-03 22:00:00   224  5.5  1.5  76.0        23.0           4.0   
17413  2017-01-03 23:00:00   139  5.0  1.0  76.0        22.0           2.0   

       is_holiday  is_weekend  season  cnt_group  
17409         0.0         0.0     3.0        1.0  
17410         0.0         0.0     3.0        0.0  
17411         0.0         0.0     3.0        0.0  
17412         0.0         0.0     3.0        0.0  
17413         0.0         0.0     3.0        0.0

In [37]:
data1.cnt_group.unique()

array([0., 1.])

In [38]:
data1nparray = data1.values

In [17]:
TrainData   = data1nparray[:, 2:10] #given all the variables 
TrainLabels = data1nparray[:,[10]] #can we predict the count group 

In [18]:
TrainData

array([[3.0, 2.0, 93.0, ..., 0.0, 1.0, 3.0],
       [3.0, 2.5, 93.0, ..., 0.0, 1.0, 3.0],
       [2.5, 2.5, 96.5, ..., 0.0, 1.0, 3.0],
       ...,
       [5.5, 1.5, 78.5, ..., 0.0, 0.0, 3.0],
       [5.5, 1.5, 76.0, ..., 0.0, 0.0, 3.0],
       [5.0, 1.0, 76.0, ..., 0.0, 0.0, 3.0]], dtype=object)

In [19]:
TrainLabels

array([[0.0],
       [0.0],
       [0.0],
       ...,
       [0.0],
       [0.0],
       [0.0]], dtype=object)

In [20]:
TrainData.astype('float64')
TrainLabels.astype('float64')

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [21]:
TrainData = tf.convert_to_tensor(TrainData, np.float32)
TrainLabels = tf.convert_to_tensor(TrainLabels, np.float32)


In [41]:
#initially trying with 2 layers
model = keras.Sequential([
#    keras.layers.Flatten(input_shape=(1, 6)),
    keras.layers.Dense(50, activation=tf.nn.softmax),
    keras.layers.Dense(60, activation=tf.nn.relu),
    keras.layers.Dense(70, activation=tf.nn.tanh)
    #keras.layers.Dense(10, activation=tf.nn.relu)
    #relu, softmax, tanh
])

In [42]:
#model = Sequential()
#model.add(Dense(64, kernel_initializer='uniform', input_shape=(10,)))
#model.add(Activation('softmax'))
model.compile(optimizer='adam', #optimizer='sgd',  
              loss='sparse_categorical_crossentropy', 
              metrics=['accuracy'])
#sgd = keras.optimizers.SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
#model.compile(loss='mean_squared_error', optimizer=sgd, metrics = ['accuracy'])

In [43]:
model.fit(TrainData, TrainLabels, epochs=50)

Epoch 1/50
544/544 ━━━━━━━━━━━━━━━━━━━━ 1s 361us/step - accuracy: 0.5890 - loss: 1.8617
Epoch 2/50
544/544 ━━━━━━━━━━━━━━━━━━━━ 0s 335us/step - accuracy: 0.7177 - loss: 0.5554
Epoch 3/50
544/544 ━━━━━━━━━━━━━━━━━━━━ 0s 338us/step - accuracy: 0.7319 - loss: 0.5237
Epoch 4/50
544/544 ━━━━━━━━━━━━━━━━━━━━ 0s 339us/step - accuracy: 0.7332 - loss: 0.5230
Epoch 5/50
544/544 ━━━━━━━━━━━━━━━━━━━━ 0s 335us/step - accuracy: 0.7346 - loss: 0.5158
Epoch 6/50
544/544 ━━━━━━━━━━━━━━━━━━━━ 0s 376us/step - accuracy: 0.7324 - loss: 0.5224
Epoch 7/50
544/544 ━━━━━━━━━━━━━━━━━━━━ 0s 333us/step - accuracy: 0.7439 - loss: 0.5063
Epoch 8/50
544/544 ━━━━━━━━━━━━━━━━━━━━ 0s 333us/step - accuracy: 0.7125 - loss: 0.5396
Epoch 9/50
544/544 ━━━━━━━━━━━━━━━━━━━━ 0s 349us/step - accuracy: 0.7214 - loss: 0.5265
Epoch 10/50
544/544 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - accuracy: 0.7288 - loss: 0.5291
Epoch 11/50
544/544 ━━━━━━━━━━━━━━━━━━━━ 0s 370us/step - accuracy: 0.7237 - loss: 0.5314
Epoch 12/50
544/544 ━━━━━━━━━━

In [30]:
train_loss, train_acc = model.evaluate(TrainData, TrainLabels)
print('Train accuracy:', train_acc)

544/544 ━━━━━━━━━━━━━━━━━━━━ 0s 255us/step - accuracy: 0.7589 - loss: 0.4787
Train accuracy: 0.7553002238273621


In [31]:
predictions = model.predict(TrainData)

544/544 ━━━━━━━━━━━━━━━━━━━━ 0s 254us/step


In [32]:
predictions

array([[0.61347455, 0.04181362, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.6807154 , 0.03577136, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.78866076, 0.0217471 , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.21192089, 0.09239599, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.20669806, 0.10264859, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.34617078, 0.16863143, 0.        , ..., 0.        , 0.        ,
        0.        ]], dtype=float32)

In [49]:
# For classification, you might convert these probabilities to class labels:
predicted_labels = predictions.argmax(axis=1)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(TrainLabels, predicted_labels)
print(cm)

[[7377 1326]
 [2933 5769]]


In [ ]:
#create a train/test/validation set 